future: true
permalink: /:title/
url: http://minxinzhong.github.io
name: Minxin
author: Minxin
qq: 597506441
email: 597506441@qq.com

duoshuo: Minxin
beian: 
cnzz: 
weibo: 
github: github.com/minxinzhong
about: "这里是 Minxin 的个人博客，创建于 2018 年。"

safe: true
paginate: 20
